# Generated by Django 6.0.6 on 2026-07-12 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='end_date',
            field=models.DateField(blank=True, help_text='Дата окончания аренды', null=True),
        ),
        migrations.AddField(
            model_name='ad',
            name='start_date',
            field=models.DateField(blank=True, help_text='Дата начала аренды', null=True),
        ),
    ]
