# Generated by Django 6.0.6 on 2026-07-12 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0002_ad_end_date_ad_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='image',
            field=models.ImageField(blank=True, help_text='Фото объявления', null=True, upload_to='ads_images/'),
        ),
    ]
